name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm ci

      - name: Check format
        run: npm run format:check

      - name: Run build step
        run: npm run build
        env:
          NODE_ENV: production

      - name: Save build output
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/

  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    needs: build
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Download a build output
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist/

      - name: Deploy to GH pages
        if:
        uses: crazy-max/ghaction-github-pages@v2
        with:
          build_dir: dist
          target_branch: gh-pages
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
